name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer update --prefer-dist --no-progress
      
    - name: Install PHPUnits Tests dependencies
      run: cd tests/phpunit && composer update --prefer-dist --no-progress
      
    - name: Install BeHat Tests dependencies
      run: cd tests/behat && composer update --prefer-dist --no-progress
      
    - name: Install Build Tests dependencies
      run: cd build && composer update --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run PHPUnits test suite
      run: cd tests/phpunit && ./bin/phpunit --configuration ./phpunit.xml
      
    - name: Run Behat test suite
      run: cd tests/behat && ./bin/behat
      
    - name: Run Build test suite
      run: cd build && ./build.sh
